name: Build jar file as binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download jar file
        run: |
          wget https://github.com/REAndroid/APKEditor/releases/download/V1.3.6/APKEditor-1.3.6.jar

      - name: Generate configuration file
        run: |
          java -agentlib:native-image-agent=config-output-dir=./ APKEditor-1.3.6.jar

      - name: Build binary
        run: |
          native-image -H:ReflectionConfigurationFiles=./*.json -jar ./APKEditor-1.3.6.jar APKEditor

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v3
        with:
          name: APKEditor
          path: ./APKEditor
